### ISSUE TITLE
coco dataset annotation

### ISSUE THREAD

**Issue by xiaoxiaodansisi** [tingyu215/Routing_VLPEFT#2]
Hello, I would like to ask how MSCOCO test data set annotations come from.
Traceback (most recent call last):
  File "/home/zeng/llama/two-card-llama/Routing_VLPEFT/scripts/../eval_coco.py", line 148, in <module>
    LangGenerationEvluator.coco_evaluator(gt_path=GT_PATH, result_file_path=file_path)
  File "/home/zeng/llama/two-card-llama/Routing_VLPEFT/scripts/../eval_coco.py", line 140, in coco_evaluator
    coco_gt, coco_pred = to_coco_annotation_format(gt_path, result_file_path) 
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeng/llama/two-card-llama/Routing_VLPEFT/inference/utils.py", line 76, in to_coco_annotation_format
    "annotations": gt_data["annotations"]
                   ~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'annotations'

**Comment by tingyu215** [comment]
Hi, it's the standard karpathy test annotation, and it's been on our server for quite some time. If you cannot find it, feel free to email me, and I'll send it over to you.

**Comment by xiaoxiaodansisi** [comment]
> 嗨，这是标准的 karpathy 测试注释，它已经在我们的服务器上使用了很长一段时间。如果您找不到，请随时给我发电子邮件，我会把它发送给您。

Thank you very much. Please send it to me.

**Comment by tingyu215** [comment]
Hi,

Please find it attached.

From: xiaoxiaodansisi ***@***.***>
Date: Thursday, 14 November 2024 at 11:37
To: tingyu215/Routing_VLPEFT ***@***.***>
Cc: Tingyu Qu ***@***.***>, Comment ***@***.***>
Subject: Re: [tingyu215/Routing_VLPEFT] coco dataset annotation (Issue #2)

嗨，这是标准的 karpathy 测试注释，它已经在我们的服务器上使用了很长一段时间。如果您找不到，请随时给我发电子邮件，我会把它发送给您。

Thank you very much. Please send it to me.

―

**Comment by xiaoxiaodansisi** [comment]
Hello, I have not received the attachment.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tingyu215/Routing_VLPEFT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月14日(星期四) 晚上8:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tingyu215/Routing_VLPEFT] coco dataset annotation (Issue #2)





 
Closed #2 as completed.

**Comment by tingyu215** [comment]
hi, it should appear in your email associated with your github account. If you don't see it, please send an email to tingyu.qu at kuleuven.be and I'll send it again.
